# Generated by Django 4.1.6 on 2023-02-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'электроника'), ('fruits', 'фрукты'), ('cosmetics', 'косметика'), ('drinks', 'напитки'), ('meat', 'мясо'), ('other', 'разное')], default='other', max_length=256, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена'),
        ),
    ]
